export const string = {
    signIn: "Sign In",
    signUp: "Sign Up",
    email: "Email",
    password: "Password",
    yourUsername: "Username",
    goHome: "I'm out",
    goQueue: "Join queue",
    cannotLoadMap: "Cannot load map",
    go: "Go",
    helmetOn: "Helmet ok",
    helmet: "Helmet",
    maskOn: "Mask ok",
    mask: "Mask",
    letGo: "Let's Go!",
    moreMeat: "More meat",
    moreScallion: "More scallion",
    chiliSauce: "Chili sause",
    order: "Order!",
    close: "Close",
    hungry: "Hungry?",
    male: "Male",
    female: "Female",
    other: "Other",
    goodMorning: "Good morning!",
    goodAfternoon: "Good afternoon!",
    goodEvening: "Good evening!",
    goodNight: "Good night!",
    fill: "Something is waitting to full fill",
    fillUsername: "Ưhat can I call you?",
    fillGender: "Gender is missing!",
    locationSign: "If you haven't turn location on. Tủn it on and open app again.",
    mapSign: "Could not load map. \n Or not.",
    chatHolder: "...",
    send: "Send"
}